// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/tedoham/coins-api/service (interfaces: AccountService)

// Package mock is a generated GoMock package.
package mock

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	dto "github.com/tedoham/coins-api/dto"
	errs "github.com/tedoham/coins-api/errs"
)

// MockAccountService is a mock of AccountService interface.
type MockAccountService struct {
	ctrl     *gomock.Controller
	recorder *MockAccountServiceMockRecorder
}

// MockAccountServiceMockRecorder is the mock recorder for MockAccountService.
type MockAccountServiceMockRecorder struct {
	mock *MockAccountService
}

// NewMockAccountService creates a new mock instance.
func NewMockAccountService(ctrl *gomock.Controller) *MockAccountService {
	mock := &MockAccountService{ctrl: ctrl}
	mock.recorder = &MockAccountServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAccountService) EXPECT() *MockAccountServiceMockRecorder {
	return m.recorder
}

// ListAllAccount mocks base method.
func (m *MockAccountService) ListAllAccount() ([]dto.AccountResponse, *errs.AppError) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListAllAccount")
	ret0, _ := ret[0].([]dto.AccountResponse)
	ret1, _ := ret[1].(*errs.AppError)
	return ret0, ret1
}

// ListAllAccount indicates an expected call of ListAllAccount.
func (mr *MockAccountServiceMockRecorder) ListAllAccount() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListAllAccount", reflect.TypeOf((*MockAccountService)(nil).ListAllAccount))
}

// ListAllPayments mocks base method.
func (m *MockAccountService) ListAllPayments() ([]dto.TransactionResponse, *errs.AppError) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListAllPayments")
	ret0, _ := ret[0].([]dto.TransactionResponse)
	ret1, _ := ret[1].(*errs.AppError)
	return ret0, ret1
}

// ListAllPayments indicates an expected call of ListAllPayments.
func (mr *MockAccountServiceMockRecorder) ListAllPayments() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListAllPayments", reflect.TypeOf((*MockAccountService)(nil).ListAllPayments))
}

// MakeTransaction mocks base method.
func (m *MockAccountService) MakeTransaction(arg0 dto.TransactionRequest) (*dto.TransactionResponse, *errs.AppError) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MakeTransaction", arg0)
	ret0, _ := ret[0].(*dto.TransactionResponse)
	ret1, _ := ret[1].(*errs.AppError)
	return ret0, ret1
}

// MakeTransaction indicates an expected call of MakeTransaction.
func (mr *MockAccountServiceMockRecorder) MakeTransaction(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MakeTransaction", reflect.TypeOf((*MockAccountService)(nil).MakeTransaction), arg0)
}
